version: '2'
services:
    web:
        image: daocloud.io/library/nginx:1.9.9
        ports:
            - "80:80"
        links:
            - "phpfpm"
        volumes:
            - "~/code/php:/data"
            - "~/code/docker/lamp/nginx:/etc/nginx/conf.d/"


    phpfpm:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - "~/code/php:/data"
